---
title: "Presentation"
author: "Minsu Kim, Ariane Stark"
output: 
  beamer_presentation:
    theme: "Madrid"
    slide_level: 2
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(comment = NA)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

# Ariane packages
library(readr)
library(readxl)
library(tidyverse)
library(rpart) 
library(rpart.plot)
library(leaps)
library(glmnet)

# Minsu packages


```


```{r include=FALSE}
dat <- read_csv("case_and_demographics.csv") %>%
  subset(select = -c(1)) %>% 
  subset(select = c(1,3:4,2,5:6,43,56:61 )) %>% 
  mutate(Cum_Case_Median = cut_number(cum_case,2, labels= c(0,1))) %>% 
  na.omit() #removes Rio Arriba County NM which has NA in the pov. dem.
```

# Introduction 

## Data Set Overview

Overview of our data set choices and question

## Our Variables

list of variables

## Our Variables: Plots

3x3 grid of the predictors


# Simple Linear Regression

## Slide Name

slide text



# Subset Selection

## Slide Name

slide text



# Shrinkage Methods

## Slide Name

slide text


# Classification

## Slide Name

slide text


# Conclusion

## Slide Name

slide text




